### ISSUE TITLE
"The operation can't be completed because the item X is in use."

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/empty-trash#13]
Can/should `empty-trash` be able to properly empty the trash similarly to `rm -rf ~/.Trash/*`?

`empty-trash --force`?

**Comment by sindresorhus** [comment]
What OS? Why should it do that?

**Comment by bfred-it** [comment]
Sorry, I mean OS X 10.11

It could do that because it's a command to empty the trash but it doesn't actually empty the trash since files in use can't be removed. It does follow the OS' native behavior, but _that_ doesn't really do what I'm telling it to do: the trash won't be empty.

**Comment by sindresorhus** [comment]
macOS used have a trick to work around that. If you used "Empty trash securely" it would empty it regardless of "files in use". That option went away in El Capitan. I don't think there's any good way to do this now other than `rm -rf`, but I don't want to do that.
