### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by Niels-NTG** [sindresorhus/empty-trash#4]
I would get it if you think this completely overcomplicates stuff, But I would like to have a verbose function that prints out the current available storage space (one line for each mounted drive), followed by a log of each file that gets deleted (could be limited to only the top-level files and folders) and concluded with a line with the current storage space now that the trash has been emptied (again, one separate line for each mounted drive).

**Comment by sindresorhus** [comment]
Way over complicating it yes. You can do that yourself with some commands before empty-trash and create a shell alias.
