### ISSUE TITLE
doesn't empty trashes on other partitions

### ISSUE THREAD

**Issue by tborychowski** [sindresorhus/empty-trash#9]
I have an ntfs partition mounted in ubuntu and this doesn't empty its trash.
The nautilus trash can do that (as it shows an aggregated view of all trashes from all disks).

The solution might be to list all mounted drives ([drivelist](https://github.com/resin-io/drivelist)), find the correct location of trash folders on these (e.g. `/mnt/drive123/.Trash-1000/`) and clean all of them.

If you're interested I could try to make a PR with this sometime.

**Comment by sindresorhus** [comment]
Sure, a PR would be appreciated :) I haven't touched the Linux related code. That was all @kevva.

**Comment by tborychowski** [comment]
I created a PR. Not sure if I fit in with the code style exactly, feel free to edit, comment or reject if you don't like :-)

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/empty-trash/commit/09c31beacf4e593d69dfcd8b9956c02fbf4843c7.
